install.packages("tidyverse")
install.packages("patchwork")
install.packages("caret")
install.packages("boot")
install.packages("magick")
install.packages("scales")
install.packages("colorspace")
install.packages("ggrepel")
install.packages("lme4")
install.packages("gsbm")
install.packages("ggraph")
install.packages("tidygraph")
install.packages("reticulate")

library(reticulate)
conda_create("mamm")
use_condaenv("mamm")
conda_install("mamm", c("openai","tiktoken") )
